apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: default
  annotations:
    azure.workload.identity/client-id: {{ .Env.AZURE_USER_ASSIGNED_IDENTITY_CLIENT_ID }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: client
      containers:
        - name: client
          image: {{ .Env.SERVICE_CLIENT_IMAGE_NAME }}
          env:
            - name: ENDPOINT
              value: {{ .Env.DTS_ENDPOINT }}
            - name: TASKHUB
              value: {{ .Env.DTS_TASKHUB_NAME }}
            - name: AZURE_CLIENT_ID
              value: {{ .Env.AZURE_USER_ASSIGNED_IDENTITY_CLIENT_ID }}
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
